# 签到所得的名称，度量单位
integral_type:
  name: "奶茶券"
  unit: "张"


# 签到初始所得
integral: 5
# 连续签到所额外获得
continuous:
#   连续奖励递增最大天数
  max_day: 30
#   连续签到天数 * increase
  increase: 1


# 签到回复
# 按照连续签到次数依次回复
reply_true:
  - "好啦好啦，给{nickname}签到啦，今日获得{get_integral}{unit}{name}（[本月累计{month_signs}][连续签到{continuous}]）"

# 按照重复签到次数依次回复
reply_false:
  - "您今天已经签到过了哟！"
  - "本小姐都说了你今天已经签到过了啦！(｡•ˇ‸ˇ•｡)"
  - ">_< 又来！本小姐不是说了签到过了吗！Ծ‸ Ծ"
  - "喂，你是在和戏弄本小姐吗 →_→ ？明明说了这么多次已经签到过了！"
  - "再说的话本小姐不想理你了QAQ"
  - ""
  - "不给签到！"
  - "_(:з」∠)_以后也不想给了！"
  - "再说就真没签到机会了！…(´ºωº｀)"
  - "好啦好啦我怕你了行了吧！~>_<~"
  - "你再骚扰我就..."
  - ""

# 会将消息由上至下合并发送
reply_query:
  - "  今日签到：{is_day_login}"
  - "  {name}：{integral}{unit}"
  - "  称呼：{nickname}"
  - "  好感度：{liking}"
  - "  与您相识：{meets}天"
  - "  累计签到：{signs}次"
  - "  连续签到：{continuous}天"
  - "  本月累计：{month_signs}次"